import {chromium,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const bank=JSON.parse(readFileSync('src/data/questions.json','utf8'));
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/');
await expect(page.getByRole('heading',{name:'Your next chapter starts here.'})).toBeVisible();
await page.locator('.size-buttons button').filter({hasText:'15'}).click();
await expect(page.locator('.range-grid button').nth(1)).toHaveText('16–30');
await page.locator('.size-buttons button').filter({hasText:'10'}).click();
await page.getByRole('button',{name:'Start session',exact:true}).click();
await expect(page.locator('.question-tags')).toContainText('Source #1');
await page.locator('.dropdown-fields select').nth(0).selectOption('0');
await page.locator('.dropdown-fields select').nth(1).selectOption('1');
await page.getByRole('button',{name:'Flag for review'}).click();
await page.getByRole('button',{name:'Next question'}).click();
await page.locator('.options input').nth(2).check();
await page.getByRole('button',{name:'Pause test'}).click();
await expect(page.getByRole('heading',{name:'A moment to recharge.'})).toBeVisible();
const paused=await page.locator('.session-clock>span').textContent();
await page.waitForTimeout(1100);
expect(await page.locator('.session-clock>span').textContent()).toBe(paused);
await page.reload();
await page.getByRole('button',{name:/Test in progress/}).click();
await expect(page.locator('.options input').nth(2)).toBeChecked();
await page.getByRole('button',{name:'Go to question 4',exact:true}).click();
await page.locator('.matrix fieldset').nth(0).getByLabel('No',{exact:true}).check();
await page.locator('.matrix fieldset').nth(1).getByLabel('Yes',{exact:true}).check();
await page.locator('.matrix fieldset').nth(2).getByLabel('No',{exact:true}).check();
await page.getByRole('button',{name:'Go to question 5',exact:true}).click();
await page.locator('.drag-option').nth(3).dragTo(page.locator('.drop-slot').nth(0));
await expect(page.locator('.drop-slot select').nth(0)).toHaveValue('3');
await page.locator('.drag-option').nth(0).click();
await page.getByRole('button',{name:'Place here'}).nth(1).click();
await expect(page.locator('.drop-slot select').nth(1)).toHaveValue('0');
await page.screenshot({path:'tmp/matching.png',fullPage:true});
await page.getByRole('button',{name:'Finish & review'}).click();
await page.getByRole('button',{name:'Submit & see results'}).click();
await expect(page.getByRole('heading',{name:'Practice done. Knowledge gained.'})).toBeVisible();
await expect(page.locator('.result-message')).toContainText('8 of 17 available points');
await page.locator('.review-item summary').first().click();
await expect(page.locator('.review-banner').first()).toContainText('2 / 2 points');
await page.screenshot({path:'tmp/results.png',fullPage:true});
await page.getByRole('button',{name:'My progress',exact:true}).click();
await expect(page.locator('.history-row')).toHaveCount(1);
await page.reload();
await expect(page.locator('.history-row')).toHaveCount(1);
// Check the multi-select format through the library.
await page.getByRole('button',{name:/Question library/}).click();
await page.getByRole('textbox',{name:'Search questions'}).fill('135');
await page.locator('.library-row').click();
await expect(page.locator('.options input[type=checkbox]')).toHaveCount(5);
await page.locator('.options input').nth(2).check();await page.locator('.options input').nth(4).check();
await page.getByRole('button',{name:'Finish session',exact:true}).click();await page.getByRole('button',{name:'Submit & see results'}).click();
await expect(page.locator('.score-ring strong')).toHaveText('100%');
// All 135 questions mount and every source exhibit loads.
await page.evaluate(ids=>localStorage.setItem('foundry:session',JSON.stringify({id:'qa-all',ids,answers:{},flags:[],index:0,elapsed:0,runningSince:Date.now(),basis:'reviewed',label:'QA all formats'})),bank.map(q=>q.id));
await page.reload();await page.getByRole('button',{name:/Test in progress/}).click();
for(const q of bank){await page.getByRole('button',{name:`Go to question ${q.id}`,exact:true}).click();await expect(page.locator('.question-tags')).toContainText(`Source #${q.id}`);if(q.images.length){const image=page.locator('.exhibit img').first();await expect(image).toHaveJSProperty('complete',true);expect(await image.evaluate(i=>i.naturalWidth)).toBeGreaterThan(0);}}
// Ordering does not allow duplicate actions; moving a selection clears its old slot.
await page.getByRole('button',{name:'Go to question 108',exact:true}).click();
await page.locator('.drop-slot select').nth(0).selectOption('2');await page.locator('.drop-slot select').nth(1).selectOption('2');
await expect(page.locator('.drop-slot select').nth(0)).toHaveValue('');
await expect(page.locator('.drop-slot select').nth(1)).toHaveValue('2');
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
await mobile.goto('http://127.0.0.1:5173/');
expect(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
await mobile.screenshot({path:'tmp/mobile.png',fullPage:true});
await mobile.getByRole('button',{name:'Start session',exact:true}).click();
expect(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
await mobile.getByRole('button',{name:'Go to question 5',exact:true}).click();
await mobile.locator('.drag-option').nth(3).click();await mobile.getByRole('button',{name:'Place here'}).nth(0).click();
await expect(mobile.locator('.drop-slot select').nth(0)).toHaveValue('3');
await mobile.screenshot({path:'tmp/mobile-question.png',fullPage:true});
expect(errors).toEqual([]);console.log('PASS: ranges, session persistence, pause timer, radio, checkbox, matrix, drag/drop, touch matching, ordering, score, review, history, all 135 cards, all source images, mobile overflow, no React errors.');
await browser.close();
